esphome:
  name: test-esp32-device
  friendly_name: test-esp32-device

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

wifi:
  ssid: !secret WiFi_SSID
  #  password: !secret WiFi_Password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret AP_Password

# Enable Home Assistant API
api:
  # encryption:
  #   key: !secret encryption_key

ota:
  - platform: esphome
  # password: !secret OTA_Password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400khz
  scan: True

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    lambda: |-
      it.image(0, 0, id(hello_world), COLOR_OFF, COLOR_ON);
      it.line(0, 7, 50, 7);

image:
  - file: "../images/hello_world.png"
    id: hello_world
    type: grayscale

switch:
  - platform: gpio
    name: relay
    pin: GPIO27
    id: relay
    restore_mode: restore_default_off

button:
